### ISSUE TITLE
Update koalixcrm to django 2.1

### ISSUE THREAD

**Issue by scaphilo** [scaphilo/koalixcrm#239] opened 2018-11-17 21:08 UTC

**Comment by yurman-cc** [comment] 2018-12-10 22:32
Hey guys! How's Django 2.1 port going? ETA? Let me know if you need help

**Comment by scaphilo** [comment] 2018-12-12 19:54
Hello yurman-cc. I think I will take care of this topic in the next month.

Anyway your help would be highly appreciated. So for instance if you could start to fix the dependencies I would later take over the branch and take care of fixing the issues in the code. Hopefully there are not too many issues -  i never tried it so far.

At the moment I am working on the automated deployment of all branches (fix issue #140) Because i have to do this with a script running on the Jenkins server this is not visible in this repository.

**Comment by yurman-cc** [comment] 2018-12-17 00:43
OK, so I got around to this and have checked in the change in my fork https://github.com/yurman-cc/koalixcrm but the testing has been very limited (only as far as it doesn't break my site). This should also be OK with the Django 1.11 (db migration is needed though). Mostly, it's just about adding explicit param "on_delete=models.CASCADE" (I believe this is the default param in 1.11 so no actual change) when creating ForeignKey. I guess you should just check if some of them might need to be set to NULL instead of CASCADE by design after all. Also, I have run it with the most recent django-filebrowser==3.11.1 +django-grappelli (it had to be updated for 2.1.4)

Let me know if I should create a pull request (I'm fine either way as this change is enough for me for now)

Cheers /Alex

**Comment by scaphilo** [comment] 2018-12-20 21:40
Hello Alex
Thanks a lot for the first investigation. I will take care of this fork immediately after i finished the issue #140 . The continous deployment is trickier than I initially expected

**Comment by scaphilo** [comment] 2019-01-06 16:31
@yurman-cc: I have created a pull request from your master. There have been several libraries and even migration files that need to be updated. I would recommend you are going to draw from the develop branch once i have completed the work.

**Closed** 2019-01-15 20:23 UTC
Labels: feature, major
